// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcwtZFhSu2No0ZXwiwSGvx8t8Pj97dyes',
    appId: '1:709434884463:web:3ca4c1ff313781924ca89a',
    messagingSenderId: '709434884463',
    projectId: 'stray-pawsitive-8cff4',
    authDomain: 'stray-pawsitive-8cff4.firebaseapp.com',
    storageBucket: 'stray-pawsitive-8cff4.firebasestorage.app',
    measurementId: 'G-M9R2T4LS5G',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXBzD0znleRP0P4H9a_R-i2gjYVAVjXRk',
    appId: '1:709434884463:ios:2ab0ce69913048804ca89a',
    messagingSenderId: '709434884463',
    projectId: 'stray-pawsitive-8cff4',
    storageBucket: 'stray-pawsitive-8cff4.firebasestorage.app',
    iosBundleId: 'com.example.strayPawsitive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXBzD0znleRP0P4H9a_R-i2gjYVAVjXRk',
    appId: '1:709434884463:ios:2ab0ce69913048804ca89a',
    messagingSenderId: '709434884463',
    projectId: 'stray-pawsitive-8cff4',
    storageBucket: 'stray-pawsitive-8cff4.firebasestorage.app',
    iosBundleId: 'com.example.strayPawsitive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcwtZFhSu2No0ZXwiwSGvx8t8Pj97dyes',
    appId: '1:709434884463:web:6f81d3c68d9407dc4ca89a',
    messagingSenderId: '709434884463',
    projectId: 'stray-pawsitive-8cff4',
    authDomain: 'stray-pawsitive-8cff4.firebaseapp.com',
    storageBucket: 'stray-pawsitive-8cff4.firebasestorage.app',
    measurementId: 'G-CPL1DVG52F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7MCC75IDpQOEnTazWqyLrIWivJF89QQc',
    appId: '1:709434884463:android:29d402f6a72fc7d64ca89a',
    messagingSenderId: '709434884463',
    projectId: 'stray-pawsitive-8cff4',
    storageBucket: 'stray-pawsitive-8cff4.firebasestorage.app',
  );

}